name: PR Check
run-name: ${{ github.actor }} attempting to merge a PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Lint checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
  build:
    name: Successful build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build code
        run: npm run build
